// Ročno preverjen izbor največjih slovenskih postaj (fallback, če imenik ni dosegljiv).
// Vsi tokovi pripadajo izdajateljem postaj. / Curated fallback list.
window.FALLBACK_STATIONS = [
  { name: "Val 202", url: "https://mp3.rtvslo.si/val202", homepage: "https://val202.rtvslo.si", tags: "pop,rock,informative", codec: "MP3", bitrate: 128 },
  { name: "Radio Slovenija – 1. program", url: "https://mp3.rtvslo.si/ra1", homepage: "https://www.rtvslo.si/radio", tags: "news,culture", codec: "MP3", bitrate: 128 },
  { name: "ARS – 3. program", url: "https://mp3.rtvslo.si/ars", homepage: "https://ars.rtvslo.si", tags: "classical,culture,jazz", codec: "MP3", bitrate: 128 },
  { name: "Radio Si International", url: "https://mp3.rtvslo.si/rsi", homepage: "https://www.rtvslo.si/radiosi", tags: "news,english,pop", codec: "MP3", bitrate: 128 },
  { name: "Radio Koper", url: "https://mp3.rtvslo.si/kp", homepage: "https://www.rtvslo.si/koper", tags: "regional,pop", codec: "MP3", bitrate: 128 },
  { name: "Radio Maribor", url: "https://mp3.rtvslo.si/mb", homepage: "https://www.rtvslo.si/maribor", tags: "regional,pop", codec: "MP3", bitrate: 128 },
  { name: "Radio 1", url: "https://live.radio.si/Radio1", homepage: "https://www.radio1.si", tags: "pop,top 40", codec: "MP3", bitrate: 128 },
  { name: "Radio Antena", url: "https://live.radio.si/Antena", homepage: "https://www.radioantena.si", tags: "pop,top 40", codec: "MP3", bitrate: 128 },
  { name: "Radio Center", url: "https://live.radio.si/Center", homepage: "https://www.radiocenter.si", tags: "pop,top 40", codec: "MP3", bitrate: 128 },
  { name: "Radio Aktual", url: "http://195.95.158.131:9080/", homepage: "https://www.radioaktual.si", tags: "ex-yu,folk,pop", codec: "MP3", bitrate: 128 },
  { name: "Radio Veseljak", url: "http://195.95.158.131:9060/", homepage: "https://www.veseljak.si", tags: "folk,narodna", codec: "MP3", bitrate: 128 },
  { name: "Radio Ognjišče", url: "https://live.radio-ognjisce.si:8080/ognjisce.mp3", homepage: "https://www.radio-ognjisce.si", tags: "christian,talk", codec: "MP3", bitrate: 128 },
  { name: "Radio Študent", url: "https://stream.radiostudent.si:8000/live.mp3", homepage: "https://radiostudent.si", tags: "alternative,student", codec: "MP3", bitrate: 128 },
  { name: "Rock Radio", url: "http://stream.rockradio.si:9034/;", homepage: "https://www.rockradio.si", tags: "rock", codec: "MP3", bitrate: 128 },
  { name: "Radio Capris", url: "https://live.radio.si/Capris", homepage: "https://www.radiocapris.si", tags: "pop,primorska", codec: "MP3", bitrate: 128 },
  { name: "Radio City", url: "https://live.radio.si/City", homepage: "https://www.radiocity.si", tags: "pop", codec: "MP3", bitrate: 128 },
  { name: "Radio Ekspres", url: "https://live.radio.si/Ekspres", homepage: "https://www.radioekspres.si", tags: "oldies,pop", codec: "MP3", bitrate: 128 },
  { name: "Radio S", url: "https://live.radio.si/RadioS", homepage: "https://www.radios.si", tags: "pop", codec: "MP3", bitrate: 128 },
  { name: "Radio Hit", url: "https://live.radio.si/Hit", homepage: "https://www.radiohit.si", tags: "pop", codec: "MP3", bitrate: 128 },
  { name: "Radio Krka", url: "https://live.radio.si/Krka", homepage: "https://www.radiokrka.si", tags: "pop,regional", codec: "MP3", bitrate: 128 },
  { name: "Radio Ptuj", url: "https://live.radio.si/Ptuj", homepage: "https://www.radioptuj.si", tags: "pop,regional", codec: "MP3", bitrate: 128 },
  { name: "Radio Murski val", url: "https://live.radio.si/MurskiVal", homepage: "https://www.murskival.si", tags: "regional,pop", codec: "MP3", bitrate: 128 },
  { name: "Radio Celje", url: "https://live.radio.si/Celje", homepage: "https://www.radiocelje.si", tags: "pop,regional", codec: "MP3", bitrate: 128 },
  { name: "Radio Štajerski val", url: "https://live.radio.si/StajerskiVal", homepage: "https://www.stajerskival.si", tags: "oldies,regional", codec: "MP3", bitrate: 128 },
  { name: "Radio Koroška (Koroški radio)", url: "https://live.radio.si/KoroskiRadio", homepage: "https://www.koroski-radio.si", tags: "regional,pop", codec: "MP3", bitrate: 128 },
  { name: "Radio Triglav", url: "https://live.radio.si/Triglav", homepage: "https://www.radiotriglav.si", tags: "folk,regional", codec: "MP3", bitrate: 128 },
  { name: "Radio Gorenc", url: "https://live.radio.si/Gorenc", homepage: "https://www.radiogorenc.si", tags: "folk,gorenjska", codec: "MP3", bitrate: 128 },
  { name: "Radio Sraka", url: "https://live.radio.si/Sraka", homepage: "https://www.radiosraka.si", tags: "folk,regional", codec: "MP3", bitrate: 128 },
  { name: "Radio Maxi", url: "https://live.radio.si/Maxi", homepage: "https://www.radiomaxi.si", tags: "pop,regional", codec: "MP3", bitrate: 128 },
  { name: "Radio Rogla", url: "https://live.radio.si/Rogla", homepage: "https://www.radiorogla.si", tags: "rock,pop", codec: "MP3", bitrate: 128 },
  { name: "Radio Dur", url: "https://live.radio.si/Dur", homepage: "https://www.radiodur.si", tags: "folk", codec: "MP3", bitrate: 128 },
  { name: "Radio Robin", url: "https://live.radio.si/Robin", homepage: "https://www.radiorobin.si", tags: "pop,primorska", codec: "MP3", bitrate: 128 },
  { name: "Radio Capodistria", url: "https://mp3.rtvslo.si/capodistria", homepage: "https://www.rtvslo.si/capodistria", tags: "italian,izola", codec: "MP3", bitrate: 128 },
  { name: "Murski madžarski radio / Muravidéki Magyar Rádió", url: "https://mp3.rtvslo.si/mmr", homepage: "https://www.rtvslo.si/mmr", tags: "hungarian,minority", codec: "MP3", bitrate: 128 },
  { name: "Radio Marš", url: "https://live.radiomars.si:8443/mars.mp3", homepage: "https://www.radiomars.si", tags: "alternative,maribor", codec: "MP3", bitrate: 128 },
  { name: "Radio Terminal", url: "https://stream.radioterminal.si/live", homepage: "https://www.radioterminal.si", tags: "electronic,alternative", codec: "MP3", bitrate: 128 }
];
